#langslist.py
# Copyright (C) 2012-2013 Aleksey Sadovoy AKA Lex <lex@progger.ru>,
#ruslan <ru2020slan@yandex.ru>,
#beqa <beqaprogger@gmail.com>
#This file is covered by the GNU General Public License.
#See the file COPYING for more details.

langslist = {
	_("Automatically detect language"):"auto",
	_("Afrikaans"):"af",
	_("Albanian"):"sq",
	_("Arabic"):"ar",
	_("Armenian"):"hy",
	_("Azerbaijani"):"az",
	_("Basque"):"eu",
	_("Belorussian"):"be",
	_("Bengali"):"bn",
	_("Bulgarian"):"bg",
	_("Canada"):"kn",
	_("Catalan"):"ca",
	_("Czech"):"cs",
	_("Chinese Simplified"):"zh-CN",
	_("Chinese Traditional"):"zh-TW",
	_("Creole Haiti"):"ht",
	_("Croatian"):"hr",
	_("Danish"):"da",
	_("Dutch"):"nl",
	_("English"):"en",
	_("Estonian"):"et",
	_("Finnish"):"fi",
	_("French"):"fr",
	_("Galician"):"gl",
	_("Georgian"):"ka",
	_("German"):"de",
	_("Greek"):"el",
	_("Gujarat"):"gu",
	_("Hebrew"):"iw",
	_("Hindi"):"hi",
	_("Hungarian"):"hu",
	_("Indonesian"):"id",
	_("Irish"):"ga",
	_("Icelandic"):"is",
	_("Italian"):"it",
	_("Japanese"):"ja",
	_("Korean"):"ko",
	_("Latin"):"la",
	_("Latvian"):"lv",
	_("Lithuanian"):"lt",
	_("Macedonian"):"mk",
	_("Malay"):"ms",
	_("Maltese"):"mt",
	_("Norwegian"):"no",
	_("Persian"):"fa",
	_("Polish"):"pl",
	_("Portuguese"):"pt",
	_("Romanian"):"ro",
	_("Russian"):"ru",
	_("Serbian"):"sr",
	_("Slovak"):"sk",
	_("Slovenian"):"sl",
	_("Spanish"):"es",
	_("Swahili"):"sw",
	_("Swedish"):"sv",
	_("Tagalog"):"tl",
	_("Tamil"):"ta",
	_("Telugu"):"te",
	_("Thai"):"th",
	_("Turkish"):"tr",
	_("Ukrainian"):"uk",
	_("Urdu"):"ur",
	_("Vietnamese"):"vi",
	_("Welsh"):"cy",
	_("Yiddish"):"yi",
	_("Esperanto"):"eo"
}