#langslist.py
# Copyright (C) 2012-2013 Aleksey Sadovoy AKA Lex <lex@progger.ru>,
#ruslan <ru2020slan@yandex.ru>,
#beqa <beqaprogger@gmail.com>
#This file is covered by the GNU General Public License.
#See the file COPYING for more details.

from languageHandler import getLanguageDescription as g

langslist = {
	_("Automatically detect language"):"auto",
	g("af"):"af",
	g("sq"):"sq",
	g("ar"):"ar",
	g("hy"):"hy",
	g("az"):"az",
	g("eu"):"eu",
	g("be"):"be",
	g("bn"):"bn",
	g("bg"):"bg",
	g("kn"):"kn",
	g("ca"):"ca",
	g("cs"):"cs",
	g("zh-CN"):"zh-CN",
	g("zh-TW"):"zh-TW",
	_("Creole Haiti"):"ht",
	g("hr"):"hr",
	g("da"):"da",
	g("nl"):"nl",
	g("en"):"en",
	g("et"):"et",
	g("fi"):"fi",
	g("fr"):"fr",
	g("gl"):"gl",
	g("ka"):"ka",
	g("de"):"de",
	g("el"):"el",
	g("gu"):"gu",
	g("he"):"he",
	g("hi"):"hi",
	g("hu"):"hu",
	g("id"):"id",
	g("ga"):"ga",
	g("is"):"is",
	g("it"):"it",
	g("ja"):"ja",
	g("ko"):"ko",
	_("Latin"):"la",
	g("lv"):"lv",
	g("lt"):"lt",
	g("mk"):"mk",
	g("ms"):"ms",
	g("mt"):"mt",
	g("no"):"no",
	g("fa"):"fa",
	g("pl"):"pl",
	g("pt"):"pt",
	g("ro"):"ro",
	g("ru"):"ru",
	g("sr"):"sr",
	g("sk"):"sk",
	g("sl"):"sl",
	g("es"):"es",
	g("sw"):"sw",
	g("sv"):"sv",
	_("Tagalog"):"tl",
	g("ta"):"ta",
	g("te"):"te",
	g("th"):"th",
	g("tr"):"tr",
	g("uk"):"uk",
	g("ur"):"ur",
	g("vi"):"vi",
	_("ci"):"cy",
	_("Yiddish"):"yi",
	_("Esperanto"):"eo"
}